
#include "LinearBuilder.h"

void LinearBuilder::visit(AST::Program& node) {}
void LinearBuilder::visit(AST::Import_Decl& node) {}
void LinearBuilder::visit(AST::Field_Decl& node) {}
void LinearBuilder::visit(AST::Id_Field_Decl& node) {}
void LinearBuilder::visit(AST::Array_Field_Decl& node) {}
void LinearBuilder::visit(AST::Method_Decl& node) {}
void LinearBuilder::visit(AST::Parameter& node) {}
void LinearBuilder::visit(AST::Block& node) {}
void LinearBuilder::visit(AST::Field_Type& node) {}
void LinearBuilder::visit(AST::Method_Type& node) {}
void LinearBuilder::visit(AST::Location_Assign_Op& node) {}
void LinearBuilder::visit(AST::Location_Incr& node) {}
void LinearBuilder::visit(AST::Method_Call_Stmt& node) {}
void LinearBuilder::visit(AST::If_Else_Stmt& node) {}
void LinearBuilder::visit(AST::For_Stmt& node) {}
void LinearBuilder::visit(AST::While_Stmt& node) {}
void LinearBuilder::visit(AST::Return_Stmt& node) {}
void LinearBuilder::visit(AST::Break_Stmt& node) {}
void LinearBuilder::visit(AST::Continue_Stmt& node) {}
void LinearBuilder::visit(AST::For_Upd_Assign_Op& node) {}
void LinearBuilder::visit(AST::For_Upd_Incr& node) {}
void LinearBuilder::visit(AST::Loc_Var& node) {}
void LinearBuilder::visit(AST::Loc_Array& node) {}
void LinearBuilder::visit(AST::Minus_Expr& node) {}
void LinearBuilder::visit(AST::Not_Expr& node) {}
void LinearBuilder::visit(AST::INT_Expr& node) {}
void LinearBuilder::visit(AST::LONG_Expr& node) {}
void LinearBuilder::visit(AST::Mul_Op_Expr& node) {}
void LinearBuilder::visit(AST::Add_Op_Expr& node) {}
void LinearBuilder::visit(AST::Rel_Op_Expr& node) {}
void LinearBuilder::visit(AST::Eq_Op_Expr& node) {}
void LinearBuilder::visit(AST::Logic_Op_Expr& node) {}
void LinearBuilder::visit(AST::Loc_Expr& node) {}
void LinearBuilder::visit(AST::Method_Call_Expr& node) {}
void LinearBuilder::visit(AST::Literal_Expr& node) {}
void LinearBuilder::visit(AST::Len_Expr& node) {}
void LinearBuilder::visit(AST::Paren_Expr& node) {}
void LinearBuilder::visit(AST::Expr_Arg& node) {}
void LinearBuilder::visit(AST::String_Arg& node) {}
void LinearBuilder::visit(AST::Assign_Op& node) {}
void LinearBuilder::visit(AST::Increment& node) {}
void LinearBuilder::visit(AST::Mul_Op& node) {}
void LinearBuilder::visit(AST::Add_Op& node) {}
void LinearBuilder::visit(AST::Rel_Op& node) {}
void LinearBuilder::visit(AST::Eq_Op& node) {}
void LinearBuilder::visit(AST::Logic_Op& node) {}
void LinearBuilder::visit(AST::Literal& node) {}
void LinearBuilder::visit(AST::Int_Lit& node) {}
void LinearBuilder::visit(AST::Long_Lit& node) {}
void LinearBuilder::visit(AST::Char_Lit& node) {}
void LinearBuilder::visit(AST::Bool_Lit& node) {}
void LinearBuilder::visit(AST::Type& node) {}
void LinearBuilder::visit(AST::Id& node) {}